### ISSUE TITLE
Discussion: Split modules into separate angular-ui repos?

### ISSUE THREAD

**Issue by dylang** [angular-ui/angular-ui-OLDREPO#141]
AngularUI is one of the reasons I decided to adopt Angular but I'm nervous about the monolithic nature of housing it all in one repo and easily falling into the issues that have damaged jQuery UI reputation and helped birth the "micro-framework" movement.

If the modules were independent repos but all still under @angular-ui... 
- Issues and pull requests will be easier for us to track by module.
- Developers can be invited to contribute to the modules they feel they can help with.
- Pull requests will be easier to manage. 
- It will be easier to have experimental modules. 
- And It might encourage other developers to introduce new AngularUI modules that conformed to AngularUI coding guidelines.

Using commonly used tools like npm and grunt for publishing modules as packages or generating custom builds will be easy for developers to add to their workflow.

And what timing! Github's new notification system seems perfect for this.

**Comment by ProLoser** [comment]
I'm not sure I entirely agree with this because the directives are so tiny.
Some are under 10 lines of code. I haven't run into any problems so far
with putting all the directives together in one repo either. However, what
I think would be much more helpful is working on the build system we've
been discussing for some time.

One of the things you are able to do is NOT build AngularUI as one large
module. All the directives and filters can be used individually, as long as
you include common/module.js first. I'm very happy in how decoupled this
design is.

The idea behind our build system is similar to jQueryUI's package builder,
where you can pick and choose what components you actually want to use and
disregard the rest.

I will keep thinking about your suggestion though.

On Thu, Aug 9, 2012 at 9:06 AM, Dylan Greene notifications@github.comwrote:

> AngularUI is one of the reasons I decided to adopt Angular but I'm nervous
> about the monolithic nature of housing it all in one repo and easily
> falling into the issues that have damaged jQuery UI reputation and helped
> birth the "micro-framework" movement.
> 
> If the modules were independent repos but all still under @angular-uihttps://github.com/angular-ui...
> - Issues and pull requests will be easier for us to track by module.
> - Developers can be invited to contribute to the modules they feel
>   they can help with.
> - Pull requests will be easier to manage.
> - It will be easier to have experimental modules.
> - And It might encourage other developers to introduce new AngularUI
>   modules that conformed to AngularUI coding guidelines.
> 
> Using commonly used tools like npm and grunt for publishing modules as
> packages or generating custom builds will be easy for developers to add to
> their workflow.
> 
> And what timing! Github's new notification system seems perfect for this.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/141.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by boneskull** [comment]
I could go either way on this.  On the one hand it seems like a maintenance headache to make a separate repo for each directive, especially when some of them are so tiny.  But I do think it all of dylang's bullets are valid.  Except the last one about coding guidelines.  What coding guidelines?  :D

**Comment by pkozlowski-opensource** [comment]
I don't have very strong opinion on this split, but I guess I wouldn't do it right now. The thing is that creating new repositories would add maintenance overhead, would make the build and release system more complex etc. So while there are valid points here I would say -1 for splitting things now but +1 for coming back to the discussion when we start to see painful problems with a big repository.

On top of this we now got a grunt task in #160 that allows people to build a custom version of angular-ui (cool things @ajoslin)

**Comment by pkozlowski-opensource** [comment]
Let's keep this idea on our radar and come back to it when we've got better idea on repositories split. Closing for now.
