### ISSUE TITLE
inflector test is failing

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular-ui/angular-ui-OLDREPO#146]
inflector test is failing with:

Expected '  Here   Is My  Phone Number ' to equal 'Here Is My Phone Number'.
Error: Expected '  Here   Is My  Phone Number ' to equal 'Here Is My Phone Number'.
    at null.<anonymous> (D:/work/gitrepos/angular-ui/angular-ui/modules/filters/inflector/test/inflectorSpec.js:14:58)

**Comment by pkozlowski-opensource** [comment]
Was looking at the code of inflector impl and unfortunately the current implementation works only for simple cases. 

I've created the issue146 branch and added some more tests to expose problems I could think of. For now commented failing tests (xit) to have a clean  (passing) build. At the same time I'm not sure we should be writing our own impl, we could reuse sth (http://code.google.com/p/inflection-js/).

**Comment by ProLoser** [comment]
I thought I mentioned this in another message. I should have simplified the
test so that it passes. I am not 100% sure we should bother covering the
edge case outlined in the unit test. I don't think the CakePHP
implementation I pulled it from covers the edge case.

The reason is because the function was primarily intended for converting
between the different notations: fooBarFar => foo_bar_far => Foo Bar Far =>
FooBarFar. It was not intended to handle user-submitted text. If we make
the assumption that the inflections are only used by developers it might be
safe (or reasonable) to say that you should not have something like foo_Bar.

RFC

On Mon, Aug 13, 2012 at 9:35 AM, Pawel Kozlowski
notifications@github.comwrote:

> Was looking at the code of inflector impl and unfortunately the current
> implementation works only for simple cases.
> 
> I've created the issue146 branch and added some more tests to expose
> problems I could think of. For now commented failing tests (xit) to have a
> clean (passing) build. At the same time I'm not sure we should be writing
> our own impl, we could reuse sth (http://code.google.com/p/inflection-js/
> ).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/146#issuecomment-7697453.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by pkozlowski-opensource** [comment]
OK, so from the comments so far I would say that we should at least remove the failing test. I'm also not huge fan of re-implementing full blown impl covering edge cases: the final implementation would be non-trivial and we don't even know if people need it.

So maybe let's simply remove the failing test and let's see if anyone is coming back for more robust impl. Unless @dandoyon wants to give this impl a try, at least we've got tests now :-) Please let me know, I would really like to get rid of this failing test.

**Comment by pkozlowski-opensource** [comment]
Closed in pull request #147
