### ISSUE TITLE
Enhancement: jquery-timeago with angularjs-ui

### ISSUE THREAD

**Issue by prasad83** [angular-ui/angular-ui-OLDREPO#150]
``` javascript
angular.module('ui.directives').directive('uiTimeago', ['ui.config', '$timeout', function(uiConfig, $timeout) {
    return {
        restrict: 'A', // E(lement), C(lass), M(Comment), A(ttribute)
        link: function (scope, iElement, iAttrs) {
            $timeout(function(){
                iElement.timeago();
            });
        }
    }
}]);
```

Dependency: https://github.com/prasad83/jquery-timeago

**Comment by ProLoser** [comment]
Github is crashing for me on this page. Anyway. You should allow ECA not
just A. Also, you should be using `iAttrs.$observe()` to trigger the
`timeago()` as this way you don't need to rely on $timeout AND people can
update their timestamps. Not sure if it's safe to re-fire `timeago()`
multiple times though. Finally, it would be nice if I could do
ui-timeago="someTimestamp" rather than needing an **additional** attribute
to hold the data.

Frankly, I think it'd be better if we tried to get this sort of thing
working in ui-jq. If you don't care about updating the timestamp with
changes to the template, then support is either already there or going to
be there in the near future (I want to add an option to enable $timeout
wrapping of plugins).

On Tue, Aug 14, 2012 at 12:38 AM, prasad83 notifications@github.com wrote:

> angular.module('ui.directives').directive('uiTimeago', ['ui.config', '$timeout', function(uiConfig, $timeout) {
>     return {
>         restrict: 'A', // E(lement), C(lass), M(Comment), A(ttribute)
>         link: function (scope, iElement, iAttrs) {
>             $timeout(function(){
>                 iElement.timeago();
>             });
>         }
>     }}]);
> 
> Dependency: https://github.com/prasad83/jquery-timeago
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/150.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by ProLoser** [comment]
Passthru has $timeout now so you don't need this anyomre.
