### ISSUE TITLE
Date Picker default

### ISSUE THREAD

**Issue by pjsvis** [angular-ui/angular-ui-OLDREPO#167]
When I bind my model to a date picker with a null value the input shows 01Jan70

eg $scope.date_received=null;

Is there an easy way to get the input to be blank?

Peter

PS angular-ui is looking pretty good

**Comment by boneskull** [comment]
https://github.com/angular-ui/angular-ui/pull/164 may fix this issue

**Comment by pjsvis** [comment]
Hi there Boneskull. I will check it out.

I understand how the standard jquery-ui datepicker defaults to blank or whatever default you want to set.

But with Angular we are binding to a model which may be null. If so the date picker should respect the model and show a blank input.

I have posted a fiddle showing the behavior and how it gets worse as you add datePicker options. 

http://jsfiddle.net/pjstarifa/sXT2n/5/

Peter

**Comment by pjsvis** [comment]
Hey there Boneskull,

pull 164 certainly fixed the $scope.date_received=null; issue however the non null dates come out wrong.

For example 2012-07-20T10:00:00 appears in the input as 04Feb18 instead of 20Jul12

If you change the render function as follows it all works out fine:

```
      controller.$render = function() {
          var date;
          date = controller.$viewValue;

          if(date !== null){
              if (!(date instanceof Date)) {
                  date = new Date(date);
              }
          }

        return element.datepicker("setDate", date);
      };
```

I have forked the angular-ui repo and am still figuring my way around it.

Regards,

Peter

**Comment by pjsvis** [comment]
Hey again boneskull,

With the above changes the "should retain timezone info" test was failing. I modified it as follows:

  it 'should retain timezone information', ()->
      inject ($compile, $rootScope)->
        aDateString = angular.fromJson(angular.toJson(new Date(2012,8,18)))
        element = $compile('<input ui-date="{dateFormat: \'yy-mm-dd\'}" ng-model="x"/>')($rootScope)
        $rootScope.$apply ()->
          $rootScope.x = aDateString
        ISOString= element.datepicker('getDate').toISOString()
        ###expect(element.datepicker('getDate').toISOString().substring(0, 10)).toEqual(aDateString) ###
        expect(ISOString).toEqual(aDateString)

The angular.to/fromJson statements are equivalent to:

```
    aDateString = JSON.parse(JSON.stringify(new Date(2012,8,18)))
```

I have pushed the above changes to my fork of angular-ui at https://github.com/pjstarifa/angular-ui

I guess I should read up some more on git to figure out how to make a pull request. Currently I am in pretty much the same position as this guy: http://www.youtube.com/watch?v=CDeG4S-mJts

Regards,

Peter

**Comment by boneskull** [comment]
Yeah, we can't change the date string to a Date field because the time zones get messed up.  I am busy at the moment, but I can provide a failing test proving that we shouldn't be doing this.

**Comment by petebacondarwin** [comment]
Hi Guys
I am away from my computer but had a few minutes to play with the
directive.  Here is where I got to.
http://plnkr.co/edit/E2PJJ8
Take a look.  The directive monitors the directive specific options and the
global config for changes - you can see this if you change the date format
field in the plunk.
The directive tries to work only with Date objects.  If you pass in a
string it will parse it into a date object using the datepicker's parseDate
function and the current date format the directive is using.  This means
that the model is always converted to a Date object, even if you passed in
a string.  Therefore you need to mangle it if you want to display it - you
can use the built in Angular date filter or I wrote a little filter that
allows you to format the date object using the same format string that the
date picker uses. (This is different to the format string that the Angular
function uses).
I thought it would be nice to have a second attribute on the directive
(similar to ng-model) that linked to a scope field where the Date object is
stored formatted as a string.
I haven't been able to run any of the unit tests on this and I suspect it
will fail the one about parsing Date strings but I think that this is how
it should work and the unit test should be changed so that the dateFormat
is equal to the format of the string that is passed in.
Let me know what you think.
Cheers,
Pete

**Comment by boneskull** [comment]
Pete,

This looks like a good solution.

thanks
Chris

**Comment by jameswyse** [comment]
There's a bootstrap date picker add-on that was released today which looks pretty good.. 

http://www.dangrossman.info/2012/08/20/a-date-range-picker-for-twitter-bootstrap/

**Comment by ProLoser** [comment]
Ideally we don't want to wrap every plugin out there. You should see if
this works with the latest version of the passthru directive.

**Comment by jameswyse** [comment]
Oh I agree, I just wanted to drop the link in to you guys as it looks a bit more powerful than the current date picker and matches the other bootstrap plugins.

**Comment by ProLoser** [comment]
We only wrap the modal plugin from bootstrap at the moment, and there have
actually been a few calendar pickers out for a while, including several
bootstrap themed ones.

**Comment by petebacondarwin** [comment]
Actually this is a date 'range' picker, which is different from our current
date picker. It looks a little immature right now but I think it is worth
keeping an eye on.
Pete

... sent from my tablet
