### ISSUE TITLE
Events bug from #16

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#17]
Continuing tracking the fix for bug / pull request #16

I'll take a look at this as soon as I can.

**Summary:**

Even with this correction, there's still a problem. Using a uiEvent gives the following message:

Uncaught TypeError: Object # has no method 'apply'

This happens on your example on the angular-ui home page as well.

**Comment by ex-nerd** [comment]
With angular 1.0.1 the error now appears to be:

Uncaught TypeError: Object #<Object> has no method 'call'

**Comment by ex-nerd** [comment]
Also, the object notation in the example is broken:

{ focus : function(){alert('hi')}, blur : function(){alert('bye')} }

It appears that something in $eval doesn't like the function notation.  Whereas simply prepending a string like "events=" might make it work with the standard eval(), it doesn't seem to help with whatever additional magic is in $eval().

I don't think any of that is actually directly related to the "has no method" issue, it will also likely need to be fixed in order for Events to work as documented/expected.  Then again, it may be a bug ("feature"?) of angular itself.

**Comment by ProLoser** [comment]
What browser are you in? I've been working on the documentation for the past few hours and have not caught any bugs.

**Comment by ex-nerd** [comment]
The latest stable chrome (20.x).

**Comment by ProLoser** [comment]
@ex-nerd uiEvent has been refactored fairly significantly since the opening of this bug ticket (I think). Do you think you could check to see if the latest version is still giving you any errors? If not I can go ahead and close this ticket.

**Comment by gkielwasser** [comment]
I'm using the latest version of angular-ui and angularjs v1.0.1
I still have the error: "Uncaught TypeError: Object [object Object] has no method 'select2'" when i'm using the select2 directive.

**Comment by ProLoser** [comment]
@gkielwasser that's strange as that's a completely different directive. Are you having this error on the demo page or on a page you put together? Is there any chance you could make a fiddle reproducing the bug?

Relatedly, I'm about to push a complete rewrite for the select2 directive today that perhaps may fix the bug you mention, but frankly you shouldn't even be receiving this error if you're using ui-event and NOT ui-select2
