### ISSUE TITLE
Travis CI Integration

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#188]
I have been working on a 'Travis' branch to get TravisCI integration, but I'm running into problems. Most of the implementation has been copied over from Vojta's Testacular implementation.

Here is an example of one of the farthest implementations I had: http://travis-ci.org/#!/angular-ui/angular-ui/builds/2339664

As you can see at the bottom of the log, JASMINE is undefined. I'm not exactly sure where or how to declare it, and it seems to occur in Grunt. It doesn't help that I'm also less knowledgable about Testacular, Grunt and Jasmine in addition to Travis.

Please feel free to push experimental commits to that fork if you want to attempt the solution. Travis will attempt a new build with every new commit, and is setup to look at the Travis branch.

**Comment by pkozlowski-opensource** [comment]
Yuppiii! Got the Travis CI working on a sample grunt + testacular + angularjs project, check it here: https://github.com/pkozlowski-opensource/travis-play and the build result here: http://travis-ci.org/#!/pkozlowski-opensource/travis-play/builds/2380641 
We could do exactly the same for angular-ui!

Now, I can do changes in the travis branch but would prefer do it on a fresh one since the existing branch accumulated quite a number of experiments. On top of this I did my experiments with testacular 0.2.0.

So, I would like to propose the following:
- Could someone pleasssseee test and merge the #185? It would clean-up the existing build a bit. If someone could test in on Linux/Mac it would be great
- Then we would create a new branch and
  - Migrate to testacular 0.2.0
  - Add travis support like in the https://github.com/pkozlowski-opensource/travis-play 

Thoughts?

**Comment by pkozlowski-opensource** [comment]
Spent some time today trying to integrate my earlier experiments into angular-ui. You can see my commits in the travs2 branch (https://github.com/angular-ui/angular-ui/tree/travis2). I've managed to have Travis build & run tests but many of those tests are failing under Travis. I can see those failing tests both using testacular 0.2.0 and 0.0.17:
- 0.0.17 : http://travis-ci.org/#!/angular-ui/angular-ui/builds/2385371
- 0.2.0 : http://travis-ci.org/#!/angular-ui/angular-ui/builds/2385236

I don't know what is wrong with those tests, on my local machine I can see very random behavior, sometimes all the tests are passing, sometimes I can see the same failures as under Travis. From what I can see the tests that are failing are using heavy DOM manipulations and probably we need to learn better how to write those tests. The funny thing is that if I run one failing directive in isolation (ex. keypress) the tests are passing (http://travis-ci.org/#!/angular-ui/angular-ui/builds/2385414)!

I guess that there are too much interference going on during those tests as we are loading all the 3rd parties as those might do strange things... I hope that someone will be able to look at my experiments with a fresh mind and see what is going on with those tests...

**Comment by ProLoser** [comment]
It looks like only 40 tests are being run when I go to the third link. It
also appears that firefox is turning on midway through the file scan.
Perhaps the asynchronous behavior in grunt might also be a contributing
factor?

**Comment by pkozlowski-opensource** [comment]
@ProLoser  Dean, in this build http://travis-ci.org/#!/angular-ui/angular-ui/builds/2385414 only 43 tests are run since I'm only including 43 (have a look at: https://github.com/angular-ui/angular-ui/commit/bfefeac363b557c9c3e58449574d0ca9e9d3100b). I did this commit to illustrate that the keypress directive tests are passing when not combined with other directives and are failing when run in the whole suite.

Regarding FFox: I didn't know how to use other browsers (don't even know if Travis got them installed). I've noticed that testacular is using ffox and PhantomJS only to run its tests.

**Comment by boneskull** [comment]
Nice job.. how the heck did you get firefox to hit the tests?

**Comment by pkozlowski-opensource** [comment]
@boneskull in fact Travis will run whatever script you point it to so we might as well point it to the `grunt build` (well, `grunt` is enough). Now, the "secrets" to make the testacular run were:
- switch it to the `--single-run` mode - in this case it will start a server, run all the tests and exit
- have testacular to capture some browsers (FFox for now) automatically

So, the above works but many tests are still failing :-( And the worst part is that this is combination of tests that makes it fail... I will try to play with it a bit more, trying to pin-point which tests are guilty here. And will move to testacular 0.2.0.

**Comment by petebacondarwin** [comment]
Single run is definitely the way forward!  We should be doing this on our
desktops with grunt test - that way we don't need a grunt server for most
cases.  As long as you leave a browser open running the testacular client
then all you need to do is run testacular with single-run and there is no
need to have the separate terminal.

**Comment by pkozlowski-opensource** [comment]
Landed in master as 7880b99cc5914f2c5ba2a449b13c4bc84b4147d7. Closing.
