### ISSUE TITLE
Tooltip position not following page scroll

### ISSUE THREAD

**Issue by cambiata** [angular-ui/angular-ui-OLDREPO#2]
Hi!

Discovered a problem with the Tooltip implementation on the Demo page, it's displayed with the wrong y position when the page is scrolled.

**Comment by ProLoser** [comment]
Hmm... the fix (I think) would be to change the lines to be as follows:

``` js
$tooltip.css('left', angular.element(window).scrollLeft() + x);
$tooltip.css('top', angular.element(window).scrollTop() + y);
```

The problem with this is that the scrollLeft() and scrollTop() functions depend on jQuery as they are not natively available within Angular's packaged version.

We need to add configuration options so that you can specify if you want the tooltip to move or not.

Finally: you don't HAVE to use _our_ tooltip if you don't want to, it was just a quickly slapped together demo I made for hotch. If you include jQuery and any plugins, you can create your own wrapper directive and use that tooltip plugin instead.

**OR** you can use our ui-jq wrapper which lets you pass-through any jquery calls onto the element.

Example: http://jsfiddle.net/ProLoser/PVf9L/

Pinging @edwardhotchkiss because I don't want to start maintaining a tooltip plugin in this repo. You should consider dropping it and opting for an existing jquery solution.

**Comment by edwardhotchkiss** [comment]
Definitely going with @ProLoser on this. 

The ui:tooltip directive has been removed. Please use jQuery instead.
