### ISSUE TITLE
Docs for using angular-ui with bootstrap

### ISSUE THREAD

**Issue by SebastianStadil** [angular-ui/angular-ui-OLDREPO#207]
_Disclaimer: I'm new to AngularJS._

Bootstrap has a nice set of jQuery plugins, including http://twitter.github.com/bootstrap/javascript.html#tooltips, which is called via

``` javascript
$('#example').tooltip(options).
```

However when combined with AngularJS, this requires code to be executed every time a repeat executes / updates. I believe this is what jQuery Passthrough is intended to solve.

For instance, the following:

``` html
<div class="row" ng-repeat="thing in things">
    <div class="span1"><span class="popup" title="{{thing}}">{{thing}}</span></div>
</div>
```

Would require

``` javascript
$('.popup').tooltip();
```

to run every time "things" changes.

I can't seem to get jQuery Passthrough to work however; I was wondering if someone would be so kind to update the docs with an example of the above.

**Comment by ProLoser** [comment]
This is part of a bigger concern as different aspects of bootstrap require different solutions. The issue you point out with tooltip is something I've been pondering how to address for some while.

We could modify ui-jq to trigger late, thereby allowing `{{thing}}` to be interpolated initially, but what about when you change the value of `{{thing}}` (say via ajax)? Does tooltip() monitor and reflect changes to the title attribute? Is there a refresh method? Do we simply re-fire `tooltip()`?

I have toyed with the idea of `ui-observe` or `ui-watch` or passing a watch option to `ui-jq` but the issue is even then, what course of action should be taken is also unclear.

**Comment by ProLoser** [comment]
Actually, after reviewing the source code it looks like you could do `data-original-title="{{thing}}"`

**Comment by ProLoser** [comment]
Updated the demo site with a relevant example on how to accomplish this.
