### ISSUE TITLE
angular ui ui-validate - refresh of field status?

### ISSUE THREAD

**Issue by alexanderwilms** [angular-ui/angular-ui-OLDREPO#208]
I have a form with a div element used as select button. With the help of ui-validate I am able to set this element as required; once the user clicks on it the element is set to required = false. 
When I open the form again (without re-loading the page) the element is still set to false. Is there a way to "refresh" the ui-validate required value (e.g. by passing a true value via ng-init)?

**Comment by pkozlowski-opensource** [comment]
@alexanderwilms could you provide a jsFiddle / plunker exposing your problem? I'm kind of confused about your use case. The `ui-validate` directive can be only placed on elements using `ng-model` directive and ng-model can be only placed on form inputs, not on a div. I'm also not clear what you mean by "When I open the form again"?

Anyway, having a reproduce scenario will be needed to help you more.... Also feel free to discuss this problem on the dedicated google group.

**Comment by ProLoser** [comment]
You're talking about resetting the form when you're done right? This seems less of a ui-validate issue and more of a general question. Have you simply tried putting code that resets your form data whenever the form is emptied? Otherwise, what @pkozlowski-opensource said, we'd need to see some code to help you.

something like:

```
$scope.open = function(){
  $scope.data = {};
  $scope.validations = {};
};
```
