### ISSUE TITLE
Add support for sortable on table columns

### ISSUE THREAD

**Issue by jamesholcomb** [angular-ui/angular-ui-OLDREPO#221]
http://jsfiddle.net/jamesholcomb/bv22z/4/

some additional features that would be useful:

support tables that include spanning headers (i.e. th with colspan greater than 1)
be able to specify fixed (static) columns that are prevented from dragging

Ryan Niemeyer's knockout sortable plugin is a good reference: https://github.com/rniemeyer/knockout-sortable

**Comment by ProLoser** [comment]
I don't exactly see any examples that show his plugin supporting tables.
Table cells and headings are not elements that can exist outside of a table
or in any arbitrary situation. They do not adhere to common animation and
positioning constraints of most elements.

Have you tried putting divs or some other element INSIDE of each cell and
instead making _that_ draggable? Or alternatively not using a table at all
if you want multiple batches of cells to be moveable?

The only way someone could really add draggable functionality to a table is
by adding these elements and moving those around instead of the original
cells, however that seems to be far outside the base scope of the directive.

On Sun, Oct 7, 2012 at 7:14 AM, James Holcomb notifications@github.comwrote:

> http://jsfiddle.net/jamesholcomb/bv22z/4/
> 
> some additional features that would be useful:
> 
> support tables that include spanning headers (i.e. th with colspan greater
> than 1)
> be able to specify fixed (static) columns that are prevented from dragging
> 
> Ryan Niemeyer's knockout sortable plugin is a good reference:
> https://github.com/rniemeyer/knockout-sortable
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/221.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by ProLoser** [comment]
The way sortable works is it makes the children elements sortable. In a
table, you don't want the immediate children (thead, tbody) or even the
grandchildren (tr) or hell even the great-grandchildren (td) to be the
actual sorting elements. Instead you want to use Divs as I already
mentioned. Perhaps support should be expanded to specify what child or dom
element will be the sorting target.

On Sun, Oct 7, 2012 at 3:30 PM, Dean Sofer deansofer@gmail.com wrote:

> I don't exactly see any examples that show his plugin supporting tables.
> Table cells and headings are not elements that can exist outside of a table
> or in any arbitrary situation. They do not adhere to common animation and
> positioning constraints of most elements.
> 
> Have you tried putting divs or some other element INSIDE of each cell and
> instead making _that_ draggable? Or alternatively not using a table at
> all if you want multiple batches of cells to be moveable?
> 
> The only way someone could really add draggable functionality to a table
> is by adding these elements and moving those around instead of the original
> cells, however that seems to be far outside the base scope of the directive.
> 
> On Sun, Oct 7, 2012 at 7:14 AM, James Holcomb notifications@github.comwrote:
> 
> > http://jsfiddle.net/jamesholcomb/bv22z/4/
> > 
> > some additional features that would be useful:
> > 
> > support tables that include spanning headers (i.e. th with colspan
> > greater than 1)
> > be able to specify fixed (static) columns that are prevented from dragging
> > 
> > Ryan Niemeyer's knockout sortable plugin is a good reference:
> > https://github.com/rniemeyer/knockout-sortable
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/221.
> 
> ## 
> 
> Dean J Sofer
> DeanSofer@gmail.com
> 
> BS Computer Information Systems
> California State Polytechnic University, Pomona
> Telephone: 714-900-2254
> Website: www.DeanSofer.com
> Github: github.com/ProLoser

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by jamesholcomb** [comment]
Here is a knockout-sortable example.  The additional bindingHandlers deal with keeping column 1 static and supporting containerless binding syntax.

http://jsfiddle.net/rniemeyer/PhqVW/4/

Here is basic boilerplate sortable table example where the only thing you have to specify is "sortable" instead of "foreach".

http://jsfiddle.net/jamesholcomb/RA8uX/1/

**Comment by ProLoser** [comment]
Actually, I think if you create indexes in the array that mirror the statically placed nodes it should work perfectly.
