### ISSUE TITLE
Select2 value clear does not work

### ISSUE THREAD

**Issue by RabidArts** [angular-ui/angular-ui-OLDREPO#224]
Hi all,

It's entirely possible that I'm being an idiot, but don't see how.
I cannot set the value of the select2 box dynamically.
I'm mainly interested in clearing it - so .select2('val', '')

Here's an example jsfiddle where I've got a 2-level hierarchy, and 2 select2 boxes for each level.
The buttons do completely unexpected things.
JSFiddle: http://jsfiddle.net/PlaceboZA/5casr/5/

NOTE: This _might_ be related to #135 (setting val not working), but to be honest, the fiddle in #135 appears to work for me. Feel free to merge issues if you prefer.

Regards

**Comment by ProLoser** [comment]
You're doing it wrong.
1. Why are you setting a value using select2 when you should be using
   the model? $scope.person1 = whatever
2. You have not made a clear distinction between a value of 1 or a value
   of 2, Instead consider using $scope.person1 = items[1]
3. The instructions say NOT to use ng-options as it causes inconsistent
   behavior. Use ng-repeat on a child option
4. You are having very small blank options because you are setting the
   value to an option that is not available (such as null). Consider adding a
   data-placeholder attribute or hard-coding an empty option tag so that that
   input can be clearable, or avoid accidentally setting invalid values

**Comment by RabidArts** [comment]
Thanks very much ProLoser - my biggest problem was misreading the ng-options/ng-repeat instructions (I read it the other way around), which was complicated by my misunderstanding of the placeholder/default option.

I have everything working with a hardcoded empty option placeholder and always setting the model (not using 'val()').
Updated fiddle: http://jsfiddle.net/PlaceboZA/5casr/9/

But did stumble on a minor glitch with ng-change though:

I noticed that ng-change is firing on the initial selection in my controller.
If I revert back to a standard <select> (not select2), then this doesn't happen.
Not a big deal - I can work around this - but does this sound like a legitimate issue I should log separately?

**And in response to your points:**

I was largely concerned with using 'val()' to clear the selection - I realise now I can also do that using the model.

I'm still confused by your point #2 ... the selected value is the option value (and id), not an object.
So I don't understand how setting it to e.g. items[1] would work.
I tried this, but seem to be missing something here - do you know of an example somewhere that does this?

**Comment by ProLoser** [comment]
If you use an input tag instead of a select tab you can work with objects,
similar to the original select behavior. However it's my mistake to have
recommended that in this situation.

As for the initial firing of ng-change, it is hard to classify that as a
bug since initially select2 does occasionally modify the initial value. For
now I think you are better off working around it instead. Remember that a
watch fires when models are initialized too.

**Comment by ProLoser** [comment]
@RabidArts if you managed to get this working can we close this ticket?

**Comment by PhanHaHus** [comment]
d
