### ISSUE TITLE
List of what works / doesn't work with jquery passthrough

### ISSUE THREAD

**Issue by Narretz** [angular-ui/angular-ui-OLDREPO#227]
Wouldn't it be swell if there was a list of jquery / jquery ui core stuff that works out of the box with jquery passthrough / doesn't work? I consider it working if I simply can put ui-jq="function" on it, and it does the basic functionality.

For example.

button / buttonset: expression in label is translated into span element of button but not evaluated. Disabled state is ignored (need to find out more) -> needs custom directive

This should probably go into a wiki or something, but I wanted to discuss it here first.

**Comment by ProLoser** [comment]
We could put a wiki page or README file together, It would need three headings "Works", "Broken", "Inconsistent" etc. I don't know if it would be better as a README file or as a wiki page (since we don't have any other wiki pages). Perhaps just open a Pull Request with some sort of README file for now?

**Comment by steinerj** [comment]
Any news on this list? We're trying to get "autocomplete" to work, but we're failing miserably...

**Comment by ProLoser** [comment]
Check or this plunker: http://plnkr.co/edit/gist:4464334?p=preview

**Comment by ProLoser** [comment]
So I was about to start this file but I in all honesty can't see this being all that helpful as it gets really complicated.

I think it'd be better to explain how the directive works so that people can figure out for themselves what will work and how to circumvent behaviors that won't work.

### For example:

Bootstrap's tooltip plugin will work by default, but if you use `title="{{title}}"` subsequent changes will not be reflected. This is because bootstrap relocates the property to `data-original-title` and reuses this property every time the tooltip is reopened. This is to prevent browser's native tooltip behavior. So, a simple workaround to improve compatibility with `ui-jq` is to instead do `date-original-title="{{title}}"`. These unusual nuances and related explanations could potentially grow very large in a simple document.
I realize this may seem unacceptable to people who are using `ui-jq` in an attempt to not have to learn heavy plugin / js code but if we can make why and how this directive works more transparent it would not only enable people to decide for themselves what plugins will be supported but also teach them about how angular works and give them ideas on how to circumvent the limitations they encounter.

### Conclusion:

I agree better documentation should be created. But I think it should break down how `ui-jq` works and give a few examples so that people can wield it with greater power.

**Comment by ProLoser** [comment]
How's this? https://github.com/angular-ui/angular-ui/blob/jq/modules/directives/jq/README.md

I realize it's a bit long. Please feel free to suggest ways I can condense it so that it's easier to skim / digest.
