### ISSUE TITLE
ng-repeat is applied multiple times when placed inside a ui-map-info-window

### ISSUE THREAD

**Issue by alexbirkett** [angular-ui/angular-ui-OLDREPO#236]
The bug can be reproduced here:
http://alexbirkett.github.com/angular-ui.github.com/index.html

An array contains four items:
$scope.properties = [{name: "test"}, {name:"test2"}, {name:"test3"}, {name:"test4"}];

each item is rendered four times by ng-repeat e.g:

test
test
test
test
test2
test2
test2
test2
test3
test3
test3
test3
test4
test4

Each item is rendered five times if the array contains five items etc.

**Comment by ProLoser** [comment]
Seems to be working currently. Feel free to comment/reopen if we still fail lol.

**Comment by redbraininc** [comment]
This still appears to be broken.  Even worse, the number of renderings of each element in the ng-repeat array increases exponentially every time open() is called on the infoWindow.  I'm seeing the same behavior in my app.

**Comment by shaungrady** [comment]
It looks like it's caused by the info window being recompiled every time it's opened, on this line:
https://github.com/angular-ui/angular-ui/blob/master/modules/directives/map/map.js#L76

I don't have time to look into this until possibly this weekend or Monday, but my question is:
Does it need to be compiled more than once? Or at all? uiMapInfoWindow isn't running at an elevated priority, so ngRepeat has already been compiled by the time uiMapInfoWindow starts compiling. This may have been necessary for an older version of AngularJS, but it doesn't seem necessary today.

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-map (after confirming it's still necessary with the latest code)?

**Comment by Valorum** [comment]
Just putting this here for others: Just ran into this bug (using latest stable Angular and ui-map from master). Commented out the compile line as suggested by @shaungrady and it works properly now. (This suggests the whole decorating of the .open method can be taken out.)

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-map

Please reopen this issue there if it is still relevant.
