### ISSUE TITLE
Codemirror needs to be repainted when used in ModalWindow

### ISSUE THREAD

**Issue by OClement** [angular-ui/angular-ui-OLDREPO#245]
I have a custom directive in which I have a Modal Window.

In that modal window I have a codemirror widget.

When I first open the modal window, Codemirror seems to be correctly initialized, but won't display the content, despite the fact that the model is correctly assigned and populated (I see it in Batarang)

Any changes to the model, of even a window resize will have the content appears correctly.
## 

On a related note, if I close that modal window, change the model assigned to codemirror and reopen it, it will still show the old content (when it was closed), until a "repaint"

Any idea to work around this issue? I'm still fairly new to Angular and might not be aware of all the tools available for this.

Thanks

**Comment by ProLoser** [comment]
It would be helpful if you provided a demo on plunker or jsfiddle that
reproduces the error as I'm not sure if this is an AngularJS `$digest` that
isn't firing or if the CodeMirror directive needs to hook into something
more than it already is.

**Comment by OClement** [comment]
I will try to put something together, yes

I am kind of in a rush with that project right now so I am not sure when I'll be able to reproduce it in a fiddle or plunk.

Thanks

**Comment by pabloperalta** [comment]
Hello. I think I'm having a similar problem (if not the same). I have a few tabs, each with two codemirror textareas. Only the ones in the first tab update themselves correctly when the model is updated (I'm updating it by calling get on a resource in my actual application).

I have written a jsFiddle: http://jsfiddle.net/2hHX4/15/

When you update the content of the non-codemirror textarea in the bottom and then you press "Show console", you'll see that the value you entered is there but it is not visible until you change the content of the codemirror textarea. And if you go to the second tab, you'll see that the same thing happens. I think it has something to do with the fact that codemirror creates a whole new textarea but since javascript is not my thing I couldn't find any workaround. Specially when having many tabs and many codemirror textareas at the same time.

Hope this information helps

Pablo

**Comment by OClement** [comment]
This is what I'm experiencing, in a slightly different context.

I suspect this is due to the fact that widget is hidden when the changes happens.

Would it be possible to make sure to update the widget with the model when it gets shown/hidden? That would probably do it. I am not sure if there would be a cleaner fix for that at the time being though

**Comment by pabloperalta** [comment]
I think that being hidden represents a problem for codemirror but not exactly for angular. What I mean is that angular does update the textarea correctly but the problem is that codemirror works by hidding your textarea and showing a new one that does the actual work. It's THAT new text area that doesn't get updated, basically because it knows nothing about angular and the ng-model directive doesn't know this new text area. My guess is that the ui-codemirror directive should bind this new text area to the model. I think this is one of those link/compile stuff I don't really understand the slightest where the new text area is generated after compiling and therefore not linked to the model or to angular at all except at rendering time where a race condition could take place if the content of the text area is not ready... or something like that.

**Comment by OClement** [comment]
Linking to the model seems to work fine
Try this: http://jsfiddle.net/oclement/VzhD6/1/
just a forked version of your fiddle with Codemirror already displayed
I also added ng-model-instant to the text area at the bottom just so it updates the model as you type

1- type "12345678" in the text area at the bottom: you see Codemirror updating fine
2- hide codemirror (click hide console)
3- update the model by changing the text-area again (delete and type "1234", you'll see whjy in a minute)
4- show codemirror (click show console)

Codemirror will display the text as it was after step 1
The cursor position will be at the end of the NEW string (will be on column 4)

5- hit space or just resize the window: boom, new model displayed correctly

---

This really look like a rendering issue to me. As to how to fix it is a completely different matter as I have no ideas...

**Comment by pabloperalta** [comment]
You are absolutely right.

**Comment by OClement** [comment]
So anybody with a workaround or better yet, a solution to this?

**Comment by ProLoser** [comment]
So keep in mind I barely use CodeMirror, but after reviewing the code (for the first time) it looks like this directive really needs to be rewritten.

If you take a look, there's a watch being created here: https://github.com/angular-ui/angular-ui/blob/master/modules/directives/codemirror/codemirror.js#L57 which is re-initializing (and destroying) codeMirror every single time the model value changes. This is kind of insane and silly vs doing something like `codeMirror.setValue()`

I also am not sure if a `$parse` [version of the model](https://github.com/angular-ui/angular-ui/blob/master/modules/directives/codemirror/codemirror.js#L19) can be submitted as the first parameter for `$watch()` but I may be wrong.

When I get some time this week I will try to rewrite this and see if this fixes the problems mentioned. However if you'd like to help us out (since this is volunteered labor) you can make the changes yourself!

**Comment by OClement** [comment]
Thanks a lot for your input ProLooser
I would gladly help, but I don't feel quite confident in doing so just yet, I might end up doing bad code in something someone else like me might end up using and having problems with :smile: 

I'll start studying the directive's code more seriously and see if something good comes out of it, who knows...

**Comment by pabloperalta** [comment]
Hi ProLooser. I can tell you are a really busy man so thanks a lot for taking the time to take a look at this issue. To tell you the truth I have been trying to make it work but I'm not good enough. I'll keep trying though but I feel like a dog chasing cars right now.

**Comment by ProLoser** [comment]
Look at our other directives to see how they work. It's not that complex.
The main thing is you use the controller to set the value or get the value
from the model. The only catch is hooking into the plugin (codemirror) for
callbacks on updating the model

On Tue, Nov 6, 2012 at 1:02 PM, pabloperalta notifications@github.comwrote:

> Hi ProLooser. I can tell you are a really busy man so thanks a lot for
> taking the time to take a look at this issue. To tell you the truth I have
> been trying to make it work but I'm not good enough. I'll keep trying
> though but I feel like a dog chasing cars right now.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/245#issuecomment-10127553.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by OClement** [comment]
Quick "update":

Looking at the directive and Codemirror's API (which I'm new to as well), I didn't feel quite comfortable in trying to fix/redo the directive just now.

In the meantime, I'm just forcing the CodeMirror's instance to refresh() once it's displayed using $timeout. Not very clean or elegant, but for now it works.

I feel like I sound like a spoiled brat commenting on those issue saying I can't do it myself, so even if this ain't the place for it, I would like to take that opportunity to give my thanks to whomever put this project together and working on it. This is awesome work guys!

**Comment by ProLoser** [comment]
This is the next item on my todo list now that I finally fixed the validate specs

**Comment by ProLoser** [comment]
So I reviewed the code and it looks good to me. That being said you're sort of back to square one.

**Comment by OClement** [comment]
Ok, thanks a lot for having taken the time to look over this, it's greatly appreciated.
I've been reading a bit more about Codemirror specific discussions, and it seems to be a widely accepted reality that you should refresh the editor instance once you're sure it's being displayed, usually using some delay.

Personally I don't think this is great and that it should be considered good practice, but considering I don't have a better solution at the moment I can live with that.

That being said, there seems to be a V3 of CodeMirror in the pipes right now (saw references of it on Adobe's Brackets project here on GitHub. Looks a promising editor by the way)

So, thanks again. I think this issue can be closed then

**Comment by cymantic** [comment]
CodeMirror with the latest angular-ui and code mirror v3, still doesn't update when shown in a modal...
work around is for a textarea with id code-mirror, call this function in a $timeout call when showing the modal:

```
    var refreshCodeMirror = function() {
        var cm = $('#code-mirror')[0].nextSibling.CodeMirror;
        cm.refresh();
    };
```

**Comment by brotherdetjr** [comment]
Sure. It doesn't update still.
Solved as a directive:

<pre><code>.directive('codeMirrorModal', function() {
    return {
        restrict: 'C',
        link: function(scope, element, attrs) {
            element.on('shown', function(evt) {
                $(evt.target).find('.CodeMirror').each(function(key, value) {
                    value.CodeMirror.refresh();
                });
            });
        }
    };
});</code></pre>

**Comment by ProLoser** [comment]
@brotherdetjr the latest version of CodeMirror (on v0.4.0) will have a fix for this called uiRefresh.

You will be able to do `ui-refresh="someExpression"` and it will refresh codemirror.

A useful way to do this would be:

``` html
<div class="modal" ui-event="{shown: 'refreshCodemirror=!refreshCodemirror' }">
 ... 
  <textarea ui-codemirror ui-refresh="refreshCodemirror">
```

**Comment by brotherdetjr** [comment]
@ProLoser Thank you! Will try it a bit later :)

**Comment by cymantic** [comment]
I've been using the changes in #358 to trigger the refresh based on the onShown event to get around the $timeout issues... look forward to having the ui-refresh though

**Comment by ladariha** [comment]
How is this supposed to work? In controller, I have

```
$scope.refreshCodemirror = false
```

in HTML:

```
<textarea rows="10" data-ui-refresh="refreshCodemirror" data-ui-codemirror="{theme:'default', mode : 'text/html'}" data-ng-model="specification.desc"></textarea>
```

and once `specification` is loaded from server, I set `$scope.refreshCodemirror = true` but nothing really changes.

Edit: After changing uiRefresh, this is thrown:

```
TypeError: Cannot read property 'display' of undefined
    at clearCaches (app/js/libs/codemirror/codemirror.js:1045:11)
    at window.CodeMirror.CodeMirror.refresh (app/js/libs/codemirror/codemirror.js:3331:13)
    at http://localhost/synergy/Synergy_Client/app/lib/angular/angular.js:9163:28
    at completeOutstandingRequest (app/lib/angular/angular.js:2930:10)
    at http://localhost/synergy/Synergy_Client/app/lib/angular/angular.js:3209:7 (11:51:08:678 | error)

    at $get (app/lib/angular/angular.js:5563:24)
    at $get (app/lib/angular/angular.js:4661:18)
    at  (app/lib/angular/angular.js:9166:11)
    at completeOutstandingRequest (app/lib/angular/angular.js:2930:10)
    at  (app/lib/angular/angular.js:3209:7)
```

To workaround it:
- change angular-ui.js, line 184 to ($timeout throws some error as well) 

```
(codeMirror.refresh(codeMirror));
```

and also codemirror.js as such, line 3330:

```
 refresh: function(that) {
            clearCaches(that || this);
```

**Comment by fluggo** [comment]
Easier fix for [ladariha's problem](https://github.com/angular-ui/angular-ui/issues/245#issuecomment-13716033), which I had too:

184: $timeout(function() {codeMirror.refresh();});

**Comment by ProLoser** [comment]
@fluggo you provide no explanation of where this code goes or how you have access to the `codeMirror` object

**Comment by fluggo** [comment]
As you will.

This line: https://github.com/angular-ui/angular-ui/blob/master/modules/directives/codemirror/codemirror.js#L68

Needs to be changed from "$timeout(codeMirror.refresh);", which fails to capture the codeMirror context, to "$timeout(function() {codeMirror.refresh();});", which preserves it.

The codeMirror variable is the one declared on line 13 and set on line 35.

**Comment by ladariha** [comment]
Nice and better :) Thanks

**Comment by ajoslin** [comment]
You could also just do `$timeout(codeMirror.refresh.bind(codeMirror))`.

**Comment by fluggo** [comment]
Elegant. I'm new to this JavaScript thing!

**Comment by ProLoser** [comment]
@ajoslin what's the browser compat of that approach? And perhaps we ned a new patch submitted?

**Comment by NickCSardo** [comment]
@ajoslin Your fix worked for me. Could we get this pulled in?

**Comment by ajoslin** [comment]
It's only IE9+, so let's do the long way `$timeout(function() {codeMirror.refresh();});`
