### ISSUE TITLE
select2 with multiple are broken even after e1b22f545a

### ISSUE THREAD

**Issue by RobertLowe** [angular-ui/angular-ui-OLDREPO#26]
select2 with multiple are broken even after e1b22f545a

Tried as a select (rendered but selection either cleared all items or kept shifting items)

```
%select#project_template_groups{"ng-model" => "project_template.group_ids", "ui-select2" => "", "ng-options" => "group.id as group.name for group in groups", "ng-multiple" => "1", "multiple" => "1"}
```

Unable to get it working when an input type=hidden

```
%input{:type => "hidden", "ng-model" => "project_template.group_ids", "ui-select2" => "", "ng-options" => "group.id as group.name for group in groups", "multiple" => "1"}
```

Also can something be added to the README about using ajax vs non-ajax multi selects.

Otherwise, it's working great!

**Comment by dandoyon** [comment]
I believe there is a rewrite in progress. Thanks for feedback

--dan

**Comment by ProLoser** [comment]
I need to update the documentation, and this specific directive is constantly being touched up.

Use `<option ng-repeat>` INSTEAD of `ng-options`. I know it seems strange but it's what works best with select2.

If you choose to use ajax, use `<input ui-select2="/* your select2 config object */">`

The object you pass to ui-select2 is checked for options that select2 is already designed to leverage and then passed directly to `select2()`.

Try this out and let me know if it fixes your problem. Oh ya I forgot to build too.

**Comment by RobertLowe** [comment]
@ProLoser I swear I tried that, thanks that fixed it:

```
  %select#project_template_groups{"ng-model" => "project_template.group_ids", "multiple" => "1", "ui-select2" => ""}
    %option{"ng-repeat" => "group in groups", :value => "{{group.id}}"} {{group.name}}
```

**Comment by ProLoser** [comment]
Just pushed an updated version with this properly built.
