### ISSUE TITLE
Select2 doesn't show initial values

### ISSUE THREAD

**Issue by MykolaBilyi** [angular-ui/angular-ui-OLDREPO#263]
Select2 doesn't show initial values
This happens because it sets up the value before the actual plugin initialisation

http://plnkr.co/edit/Wckzzv?p=preview

**Comment by bvkimball** [comment]
I have this issue too.  I did this to fix it.  Its not completely right but should get you going in the right direction

```
      if(opts.initSelection) {
          var initSelection = opts.initSelection;
          opts.initSelection = function(element, callback) {
            initSelection(element, function(value) {
              controller.$setViewValue(value);
              callback(value);
            });
          };
        }
       // ADDED THIS ELSE STATEMENT 
        else {
          opts.initSelection = function(element, callback) {
              callback(controller.$modelValue);
          };
        }
```

**Comment by ProLoser** [comment]
This looks like it would be the proper fix. You should open a pull request
with the patch.

**Comment by ni-ka** [comment]
+1 the code from  bvkimball looks good, using it and it works

**Comment by philippd** [comment]
+1 i am also using bvkimballs fix and it's working

**Comment by jph00** [comment]
After applying that pull request, I have a bug if my ng-model references an id instead of an object. In the scope.$watch we have elm.select2('data', controller.$viewValue), but if ng-model refers to an id this needs to be elm.select2('val', controller.$viewValue).

At the moment, it's still very hard to get a basic 'edit' form working when in ajax mode and with minimumInputLength set, since the select2 will not display the initial value without quite a bit of work (i.e. setting initSelection to an appropriate function, and making the change above).

**Comment by ProLoser** [comment]
0414834a353f88e6dde41541c2586cad4a1237ea
