### ISSUE TITLE
Select2 form field is always dirty

### ISSUE THREAD

**Issue by ghost** [angular-ui/angular-ui-OLDREPO#268]
Upon creating Select2 element is always dirty, even if no changes were done.

This happens because we trigger 'change' event for the element.

**Comment by ProLoser** [comment]
If you create a demo I may be able to tackle this one.

**Comment by ProLoser** [comment]
I'm thinking we can do something like `ngModel.$pristine = true` right after [this line](https://github.com/angular-ui/angular-ui/blob/master/modules/directives/select2/select2.js#L67) but I it may have to occur asynchronously.

**Comment by brettatoms** [comment]
The previous comment/reference doesn't seem like the same thing since it has to do with  $dirty not being set where this is about a ui-select2 always being $dirty.  It seems to be the same as this post which has a partial workaround when using <select> but not when using <input> (which is my problem):

https://groups.google.com/forum/?fromgroups=#!searchin/angular/select$20$24pristine/angular/WoJRSej8f7g/IC_wvt2j0m0J

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-select2 (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-select2

Please reopen this issue there if it is still relevant.
