### ISSUE TITLE
FullCalendar directive - Non editable by default.

### ISSUE THREAD

**Issue by vinniefranco** [angular-ui/angular-ui-OLDREPO#277]
Is there reasoning behind removing the ability to drag and drop an event on the calendar? Also where is the functionality to change a model if the delta has changed from fullcallendar?

**Comment by joshkurz** [comment]
We have not removed the ability to drag and drop events. It depends on whether or not the event that has been created has the editable field set to true for that functionality to become present. The Events are whatever you want them to be by default. You would set the events however you please to get the desired outcome. 

To change the model if a delta has been changed, you would need to customize the directive and add in the correct eventDrop: or eventResize method. I could go ahead and add these functions into the calendar. Haven't done this yet, because there are so many different functions that can be called from inside of these methods. For instance on our version of the calendar we are making service calls every-time one of these Deltas is changed to update that event in Mongo. 

However I do think it would be useful if just the scope events were updated on eventDrop and eventResize. That is what you mean when you say changing the model if the delta changes right? That could be the core functionality and then anyone could add to it if desired.

**Comment by vinniefranco** [comment]
Thanks Josh, 

I did work with the configurations and I have a very nice prototype now. Thanks for your input

**Comment by joshkurz** [comment]
no problem. I am still going to implement a function that changes the model if the deltas change at all. This way it will show people where they should edit the code to hook up custom services to create a persistent calendar.
