### ISSUE TITLE
visualsearch.js integration

### ISSUE THREAD

**Issue by oskbor** [angular-ui/angular-ui-OLDREPO#295]
Hello there! I want to propose an integration with the [visualsearch.js](http://github.com/documentcloud/visualsearch) library. Angular and visualsearch would be an extremely powerful combination in my opinion. Keep up the good work!

**Comment by ProLoser** [comment]
We look forward to your pull request :-)

**Comment by ProLoser** [comment]
It appears that visualsearch has a dependency on jQuery 1.4+, jQuery UI, Underscore.js, Backbone.js

That's kind of... a lot... especially considering AngularJS and Backbone are too alternative frameworks.

If they are going to have a dependency on jQueryUI they might as well use the WidgetFactory instead of Backbone :/
