### ISSUE TITLE
IE Shiv

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#3]
I stubbed out an IE shiv page that I think would be very crucial for most people.

Read the notes here: http://docs-next.angularjs.org/guide/ie

It would be better if the shiv was packaged to its own file. That way instead of doing a programmatic check for IE version, people can simply wrap the script include in a set of conditional comments.

**Comment by dandoyon** [comment]
What do you think of my refactor of ie-shiv.js?

**Comment by ProLoser** [comment]
Is it tested? Been sorta busy. Looked better than what _I_ had at least so I merged.

**Comment by dandoyon** [comment]
Manually, i was planning on setting up tests section and doing some scenario and e2e

**Comment by ProLoser** [comment]
We should update this or perhaps consider a way to let people pass more directives? Or maybe we can introspect directives?

**Comment by dandoyon** [comment]
So, I know I have not been quite active here, there is only so much time in the day. In my own development. I'm finding the shiv unnecessary because I'm avoiding the new tags and using things like class="ng-view" instead.  However, having said this, I can see that if you were creating custom directives and wanted to introduce new tags then it would be essential. 

I'll take a look, i'm having issues pulling down latest from repo, git is crimping and I don't know why.

git pull -ff upstream master
error: Failed connect to angular-ui.github.com:443; Connection refused while accessing https://angular-ui.github.com/angular-ui/angular-ui.git/info/refs

**Comment by ProLoser** [comment]
Make sure you're machine is authed with git? Maybe there's a new ssh key
setup (seemed to change last i had checked).

You also don't have to work on the shiv yourself. I actually never use the
class="" approach as I greatly prefer using new directives. It's worked
great thus far already though.

On Sun, May 27, 2012 at 4:30 PM, dandoyon <
reply@reply.github.com

**Comment by dandoyon** [comment]
One would hope older versions of IE would just go away. 

thanks

**Comment by dandoyon** [comment]
I blew away and recreated my git fork and am back in biz.

**Comment by dandoyon** [comment]
I spent some time thinking of a solution for this, basically its a bit of a hack but it is pretty boilerplate.  I'm sure some sorta script could be written to autogenerate at top of the angular-ui.js files. I'm not seeing anything in the ng doc on finding defined directives and I did some looking at the module object in debugger but not finding right thing. 

http://jsfiddle.net/dandoyon/Qjyqm/

let me know what you think

**Comment by ProLoser** [comment]
Not exactly what I was thinking, I'll dig around when I catch a break myself. I'm hoping to avoid any explicit array building whatsoever, not simply name-spacing.

**Comment by dandoyon** [comment]
Agreed, less than optimal. On another note, I'm going to make a concerted effort to re-start contributing. I think what has been started is really, really good start. I'm thinking maybe you, Pete and I could do a hangout and discuss what is done and where to go from here. There are some people that I think would be keen to contribute and we could do an outreach. But I think having clear picture of future would help. Your thoughts?

**Comment by ProLoser** [comment]
Check it out: https://github.com/angular/angular.js/issues/1116

Thinking we should throw a JSON.stringify check in there too mayhaps? Even though, yes, I realize people may prefer to just get it by adding JSON2.js but it would only be in the ieshiv file anyway.

**Comment by dandoyon** [comment]
I'll take a look, thanks for reminder. I was doing some IE7 testing and actually came across this.

**Comment by ProLoser** [comment]
So I'm looking through the shiv file and I'm sorry to say this but I think half of the file is not going to work.

I was trying to understand what the bottom half of the file does (it looks like you're trying to introspect the directives like we discussed) but I talked to the core team at one of the meetups about doing things dynamically and they explained that this won't work.

The problem is that you must inject the shiv before the unkown tag is encountered. This means that it must be executed at the top of your page and before angular has loaded, and causes problems when people try to leverage lazy-loading, so we have to go back to a more static pattern.

**Comment by dandoyon** [comment]
hmmm, so it sounds like we would need an array defined in a common file that lives on in the <head> enumerating the element directives, and that angular-ui devs would need to predefine them.  Do you agree?

**Comment by pkozlowski-opensource** [comment]
Yep, this is how I see it... It is a bit of manual work but at least should buy us IE support. This brings another question: which version of IE we want to suppor? AngularJs guys are testing with IE versions starting from 8. For me IE 6 is out of the question and 7 would be painful (especially that we won't have ci for it). Thoughts?

**Comment by dandoyon** [comment]
I was thinking that there is an alternative and that is to have the build system generate the code that initializes the ieshiv array of directives. To be honest, I haven't looked much into the grunt stuff. I'm sure it could be done. For example, if we knew that the name of a directive file was the name of the directive, the build script could prepend code to initialize an array of directive names. The effort to do this may or may not be worth it. 

As far as support, IMHO, I would abandon IE7,  i know from experience, that my company still has users on IE6/7 and we went through hoops to make our charting app work with IE7 mostly because of memory issues. I actually think my company is now setting the bar at IE8.  ieshiv should need to exist. 

my 2 cents

--dan

**Comment by petebacondarwin** [comment]
I don't think that AngularJS supports <IE8!
The only difficulty with generating the code is that some of the directives
may not be element-based but attribute-based.
I think that we could get away with having a simple file, say directives.js
that is manually maintained by developers.  When one creates a new
directive that will be an element you have to remember to add it there.
Pete

**Comment by pkozlowski-opensource** [comment]
+1 for supporting IE >= 8 only
+1 for starting simple and just updating a file be hand for now; we can try to automate it if this becomes a pain-point. Unless someone has a brilliant idea on how to automate things - I don't since we would have to parse directives source (to find `E` ones) and I don't think it is worth it...

**Comment by ProLoser** [comment]
Yes. We should remove the introspection and instead just make the
predefining as easy as possible.

**Comment by dandoyon** [comment]
alrighty then, i'll do the change

**Comment by dandoyon** [comment]
Please take a look, i chose to put tags inside of ieshiv, https://github.com/dandoyon/angular-ui/blob/static-ieshiv/common/ieshiv/ieshiv.js

If there are no aversions, i'll do a PR

--dan

**Comment by petebacondarwin** [comment]
Fair enough for now.
