### ISSUE TITLE
Change ui-event to evaluate expressions

### ISSUE THREAD

**Issue by ajoslin** [angular-ui/angular-ui-OLDREPO#30]
ui-event is kind of weird at the moment.  It can't evaluate expressions, only call functions.

I think it would be much more useful if we made it evaluate angular expressions each time.

``` html
<input ui-event="{'keyup': 'count = count + 1', 'click': 'count = count - 1'}">
```

``` javascript
//in the link function
events = scope.$eval(attrs.uiEvent);
for (key in events) {
  if (events.hasOwnProperty(key)) { 
    elm.bind(key, function() {
      scope.$apply(events[key]);
    });
  }
}
```

**Comment by ProLoser** [comment]
DOOO EET!

I was wondering how I would go about doing this...

Might make a similar change to several other directives too. Can you push the patch? (Make sure you pull the latest first though).

**Comment by ProLoser** [comment]
Actually in retrospect I have only 1 note (which is why this never occurred to me): I have never seen a directive where you had to encapsulate javascript/logic in quotes/a string as part of an expression. You pretty much always assume the expression is going to be executed as-is or you encapsulate the value in quotes to explicitly make it a string. But wrapping logic in quotes in order to make it executable seems sort of... backwards? Am I the only one thinking this?

**Comment by ajoslin** [comment]
Yeah, perhaps.  Lemme look at how ng-class does it and use that.

**Comment by ajoslin** [comment]
I got this working: http://plunker.no.de/edit/XuY2Q0?live=preview

I kind of had to write my own really simple parser (two string splits and a bit of replacing), think it's good enough? We can either trust people to write it so it doesn't spit errors, or maybe add some checks.

I also added something else I've wanted to have in that plunker and called it ui-event-when. If you did `<input ui-event-when="{focus: count == 5}">`, it would focus the input when count is 5.

**Comment by ProLoser** [comment]
Just a thought, wouldn't it make more sense to name the second directive 'uiTrigger'? I don't mind throwing it in the same folder though. Another thing that occurred to me is the use-cases for this behavior. I would be concerned at the possible race conditions that could be caused by this behavior, but I suppose we can just provide the behavior with a note for people to use at their own risk, etc.

The only use cases I can think of that people would want to trigger a behavior is focusing and blurring, almost everything else that you might trigger would actually cause code to execute, and creating this event-phase vs directly calling those methods might teach people poor practices. For instance, someone might trigger a button press so that the function call associated with that button gets fired, instead of just calling the function directly, etc. Blur and Focus are the two likely use-cases where native behavior is the actual intended effect, and even THEN it feels almost... confusing if that control is removed from the user.

**Comment by ajoslin** [comment]
Ok, yeah I guess it's too narrow to put in.

I see you pushed the quoted version so I'll close this

**Comment by ProLoser** [comment]
In retrospect I realized that the difference between this and lets say the
class directive is that in the class directive, both the keys and the
values can and should be evaluated at the same time.

However, what makes our situation unique is that the key is evaluated at
one time and then the value is evaluated at a later point in time. I don't
think any other directives behave this way. With that in mind, I found the
string encapsulation to be the most acceptable.

Also don't think of my pushes as the final say, I was mostly trying to
clean up the documentation and bring the code in line with it. You should
push your ui-trigger (or ui-event-call) directive. You can even add it
under the event module since it's fairly related (as I did and angularJS
does for show/hide).

I would also recommend pushing your latest version of the modal directive
(and any others) to your own fork even if they are unfinished, as it would
allow me to review and collaborate on them vs working purely with fiddles.

On Thu, Jul 5, 2012 at 4:03 AM, Andy Joslin <
reply@reply.github.com

**Comment by ajoslin** [comment]
I'm super busy the rest of the week, I'll hopefully have time this weekend to push some stuff.
