### ISSUE TITLE
ng-model not updating with select2 using ajax

### ISSUE THREAD

**Issue by evaneus** [angular-ui/angular-ui-OLDREPO#33]
I'm honestly not sure if this is a bug or just something I'm not doing correctly, but using select2 with ajax options I'm having trouble getting the model to update.

Here is a demo, in this demo the $watch function is not called upon making a selection.....
http://plunker.no.de/edit/dEhd2M

It would appear that the change event is never bound here....
https://github.com/angular-ui/angular-ui/blob/master/build/angular-ui.js#L345

It only binds if the element is not a select element and the multiple attribute is defined. I may be missing something in my configuration, but I understand from the select2 docs from my old friend Igor that it is correct to not use a select element for the ajax lookup use case.

**Comment by ProLoser** [comment]
Dammit. So it appears I fixed this on my project's copy of AngularUI but I forgot to port it over to here.

The Select2 is actually going to undergo a bit of refactoring in the near future due to some changes in AngularJS and Select2 that will require a lot less work on my part inside the directive.

Otherwise, a8375b70714327f1741dcf4cdc86273217de49c2 should have fixed it.
