### ISSUE TITLE
Typeahead directive 

### ISSUE THREAD

**Issue by GuillaumeBiton** [angular-ui/angular-ui-OLDREPO#333]
Here you can find a implementation of Bootstrap typeahead as AngularJS directive :

http://jsfiddle.net/guillaumebiton/hNxF7/

Don't really know how to contribute and purpose a commit if you find it interesting.

Hope it helps.

Regards

**Comment by pkozlowski-opensource** [comment]
@GuillaumeBiton we've got a separate repository for the bootstrap specific staff: 
https://github.com/angular-ui/bootstrap (demo here: http://angular-ui.github.com/bootstrap/) and since your directive is a native-AngularJS stuff it fits nicely into the project. 

Would be awesome if you could open a pull request in the https://github.com/angular-ui/bootstrap repository?
This would be the best way contributing to the project!

**Comment by GuillaumeBiton** [comment]
Ok I will try to open a pull request and create a branch "typeahead" in the right repository.
