### ISSUE TITLE
Date/Calendar Picker

### ISSUE THREAD

**Issue by scharissis** [angular-ui/angular-ui-OLDREPO#336]
Hi,

Firstly, thanks for angular-ui.

It seems to me that the default functionality of the calendar is broken (or at least very unintuitive). Specifically, when you select a date you can't re-select one immediately afterwards. One needs to first click-away and then back on it. This can occur, not only if one selects the wrong date and wishes to change it straight away, but also if you want to scan a number of dates.

To elaborate:
- Click on calendar text box (the calendar UI drops down)
- Click on a date (the calendar UI disappears and the textbox is populated with the chosen date)
- Click again on the textbox to pick a new date and nothing happens

I'd have made a jsfiddle/plunkr, but you can just check it out on your homepage: http://angular-ui.github.com/

Cheers,
Stefano

**Comment by ProLoser** [comment]
Sounds like a scope.apply() is missing

**Comment by scharissis** [comment]
It seems that the critical section is this one: [directive 'uiDate']

``` javascript
var updateModel = function () {
    scope.$apply(function () {
        var date = element.datepicker("getDate");
        element.datepicker("setDate", element.val());
        controller.$setViewValue(date);
        //if (element.is(":focus")){
            // TODO: fix
        //}
    });
 };
```

Is there a way to un-focus an element? That could go where I've marked 'TODO'.

**Comment by scharissis** [comment]
Aha!

This fixes it, although perhaps inelegantly:

``` javascript
var updateModel = function () {
    scope.$apply(function () {
        var date = element.datepicker("getDate");
        element.datepicker("setDate", element.val());
        controller.$setViewValue(date);
        if (element.is(":focus")){
            element.blur();    // Fix
       }
    });
 };
```

**Comment by petebacondarwin** [comment]
Hi Stefano,

Thanks for spotting this.  I am a bit worried that it would cause problems
if someone is trying to type in a date instead of clicking on the calendar.
I wonder if it would be safer to add this blur after line 42:
https://github.com/angular-ui/angular-ui/blob/master/modules/directives/date/date.js#L42
?

opts.onSelect = function (value, picker) {
              updateModel();
              scope.$apply(function() {
                userHandler(value, picker);
              });

```
          element.blur();
        };
```

Even here I am wondering if other things will get adversely affected by
this.  Any chance you could put together a pull request with a fix and we
could have a play. We would also need a failing unit test to demonstrate
the issue before the fix is committed.

Cheers,

Pete

**Comment by scharissis** [comment]
Hi Pete,

No worries; thanks for the library.

Yes, I share your concern and I'm certainly not the person to answer this question. But, running the tests would at least give us some confidence.

I'll gladly put together a pull request after giving it a more thorough look. I'm not sure how long it'll take, as I'm new to JS and Jasmine in particular. But perhaps I'll find how to mock it by looking at the existing tests.

Stefano

**Comment by petebacondarwin** [comment]
Hi Stefano,
It'll be an excellent learning opportunity for you!  The date directive has
pretty comprehensive tests that you can use to guide you.
The trickiest bit is getting testacular up and running.
Feel free to ping me with questions.
Pete

**Comment by scharissis** [comment]
I can't seem to write a failing test.

I've tried:
1. Using selectDate() consecutively a number of times and then checking for the correct Date.
2. Using selectDate() and click() and checking is(":visible")

I'm presently out of ideas. Got any?

**Comment by petebacondarwin** [comment]
I had a play with this.  You are right that we can blur inside the
updateModel as this only gets called when the date is selected or the input
is losing focus (i.e. on change event).
I have pushed a test (
https://github.com/angular-ui/angular-ui/commit/3f8a548788e36bc3a5c407402d44170cfa31444c)
and a fix (
https://github.com/angular-ui/angular-ui/commit/819fda12051979ff22a6430729495fd9ab61ddc3
)

Here is a working plunkr:
http://plnkr.co/edit/cJHd2G3csJ0G9tIQXGQn?p=preview

**Comment by scharissis** [comment]
Yes, I was going to tell you that I'd come to believe it should indeed be placed in the updateModel.

My concern here is whether or not this test covers the issue. I'm not saying it's not - I'm honestly not sure. I'd have thought you'd have to emulate clicking whilst checking the element active state. But I couldn't get that working.

Anyway, good work and I'm sorry I couldn't save you the trouble! Glad it's fixed.

**Comment by petebacondarwin** [comment]
This test definitely fails before you add the element.blur().  So it is a
valid test for something!
In this case I think it is enough, since we are not trying to test the
jQueryUI datepicker plugin, just how we are interacting with it.  It turns
out that if you don't have ng-model attached to the element then there was
no problem so it was not an issue with the plugin but with what we were
doing with ngModel.  Specifically, the updateModel method calls setDate,
which I believe sets the focus back to the input.
Pete
