### ISSUE TITLE
Add a 'view' property to ui-calendar so that people can easily switch views

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#377]
@joshkurz can you take a look at this?

Someone asked me on IRC how to switch views programmatically with fullCalendar.

The documentation says that you must do `fullCalendar('changeView', viewName)`.

At this time, there is no intuitive way to call alternative methods on DOM elements, but looking at the fullCalendar documentation, there are very few _methods_ so it might be acceptable to support a view attribute.

If used, the attribute model would be updated (2-way) with the current view mode, but if the value is changed then the calendar would switch.

On a somewhat related note, I started thinking about devising a new `ui-trigger` directive so that you can arbitrarily call jQuery code ON dom nodes post-initialization. This would mainly be targeted at passthrough first but may serve as a reusable solution if done elegantly. I will also point out that this approach may not necessarily be preferred.

**Comment by joshkurz** [comment]
Dean I think that is a good idea. It got me thinking why we don't expose the calendar object to the scope to call methods off of it. This way we will not need to wrap any function calls. Here is an example of all custom view switching buttons. http://jsfiddle.net/joshkurz/Ljq26/9/

should the ui-trigger method set a scope object = to the return of the generic plugin? this would enable any specific api call from the scope?

**Comment by ProLoser** [comment]
The ui-trigger is a side thought, for now though I think you're better off just adding a view attribute.  

## 

Dean Sofer
DeanSofer.com
714.900.2254

**Comment by joshkurz** [comment]
I would say that adding a view attribute would con-volute the directive. We can just expose the calendar element returned by the fullCalendar method giving access to any method desired. There will be more cases where people would like access to methods the fullcalendar offers like 'addEventSource' or 'removeEventSource'.  These methods should be exposed to the scope, so that the developer has full range of motion while determining how exactly to remove or add event sources to the calendar. I think this is the simplest way to offer all of the calendars api to the developer and not hold the calendar's had ever. 

Here is a link of the calendar adding and removing an event source from the scope. This is desired functionality that will be needed in the future.  http://plnkr.co/edit/PZOcOt?p=preview

**Comment by ProLoser** [comment]
@joshkurz do any open PRs or fixes address this issue? If so can you reference them and maybe we can close this issue?

**Comment by joshkurz** [comment]
#372 fixed this issue by adding the calendar to the scope and allowing the changeView function to be called from anywhere inside of the controller.
