### ISSUE TITLE
Calendar directive events not affected by array assignment

### ISSUE THREAD

**Issue by oevna** [angular-ui/angular-ui-OLDREPO#380]
See: http://jsfiddle.net/eHnHC/2/

Note that by clicking a day, the event should disappear from the calendar.

If you replace line 12 in the JavaScript pane with:

$scope.events.length = 0; 

This results in the calendar being cleared when a day is clicked. So at the moment, only Array.push seems to cause the calendar to be updated. I.e. you can't reassign a completely new set of events via [ { /_.._/ }, { /_.._/ }, ... ] notation after the calendar has been initialized.

**Comment by joshkurz** [comment]
That is because that version of the calendar is not watching the
events.length because the events have not been inserted into the calendars
options. Ng-model should be required to solve this issue. Here is a link
with your specific issue solved. http://jsfiddle.net/eHnHC/25/ That version
of the calendar is a little outdated, I would suggest using this one.
http://plnkr.co/edit/PZOcOt?p=preview

The theory behind the new edits are to expose the calendar element to the
scope, allowing any desired method calls from outside of the calendar. The
events option is no longer being used anymore either. This is to address
the issues that you bring up. Now the calendar is watching eventSources so
it can switch different arrays or source objects in and out of itself from
the scope.

On Wed, Jan 23, 2013 at 9:46 PM, oevna notifications@github.com wrote:

> See: http://jsfiddle.net/eHnHC/2/
> 
> Note that by clicking a day, the event should disappear from the calendar.
> 
> If you replace line 12 in the JavaScript pane with:
> 
> $scope.events.length = 0;
> 
> This results in the calendar being cleared when a day is clicked. So at
> the moment, only Array.push seems to cause the calendar to be updated. I.e.
> you can't reassign a completely new set of events via [ { /_.._/ }, {
> /_.._/ }, ... ] notation after the calendar has been initialized.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/380.

## 

_Josh Kurz_
http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com

**Comment by oevna** [comment]
Any idea when these plnkr version changes will be merged into angular-ui?

**Comment by oevna** [comment]
In your updated version at the plnkr link, doing this still doesn't work:

$scope.events = [{id: 999, title: 'RESERVED', start: new Date(y, m, d + 1, 19, 0), end: new Date(y, m, d + 1, 22, 30), allDay: false }];

Only this works:

$scope.events.push({id: 999, title: 'RESERVED', start: new Date(y, m, d + 1, 19, 0), end: new Date(y, m, d + 1, 22, 30), allDay: false });

And that is assuming:

eventSources: [$scope.events]

See this stripped-down version based on the one you suggested:

http://plnkr.co/edit/uR2bMu?p=preview

Even if I do this, after the calendar has been initialized, it seemingly has no effect:

$scope.uiConfig.fullCalendar.eventSources = [];

I'm very confused.

**Comment by joshkurz** [comment]
oevna looking into your plunker you bring up some good issues.
1. scope.events = [] does nothing because the directive is watching the
   length. I understand that this does change the length of the array and
   should rerender, but atm I dont know why its not either. The watch is not
   being fired I know that much, but why? The length is changing so it really
   makes no sense that its not firing.
2. scope.uiConfig.fullCalendar.eventSources = [] does nothing either, but
   if you do a combination of scope.uiConfig.fullCalendar.eventSource = [] and
   scope.events = [] the calendar will update accordingly.
3. scope.events.length = 0 works perfect. I would suggest using this to get
   rid of all events in the scopes events array.
4. the calendar is now a part of the scope, so you have access to all of
   the API's methods to remove/add events and eventSources. This can help
   solve any issue that you might be having, because now any method
   is accessible at any time. I have noticed that using the
   scope.calendar.fullCalendar() methods inside of apply does not work
   properly. I would suggest using these methods outside of the apply and
   updating your eventSources accordingly inside apply.

On Thu, Jan 24, 2013 at 6:25 PM, oevna notifications@github.com wrote:

> In your updated version at the plnkr link, doing this still doesn't work:
> 
> $scope.events = [{id: 999, title: 'RESERVED', start: new Date(y, m, d + 1,
> 19, 0), end: new Date(y, m, d + 1, 22, 30), allDay: false }];
> 
> Only this works:
> 
> $scope.events.push({id: 999, title: 'RESERVED', start: new Date(y, m, d +
> 1, 19, 0), end: new Date(y, m, d + 1, 22, 30), allDay: false });
> 
> And that is assuming:
> 
> eventSources: [$scope.events]
> 
> See this stripped-down version based on the one you suggested:
> 
> http://plnkr.co/edit/uR2bMu?p=preview
> 
> Even if I do this, after the calendar has been initialized, it seemingly
> has no effect:
> 
> $scope.uiConfig.fullCalendar.eventSources = [];
> 
> I'm very confused.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/380#issuecomment-12679763.

## 

_Josh Kurz_
http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com

**Comment by oevna** [comment]
Not having an $scope variable watched by Angular removes some of the magic of Angular, IMO. But I definitely think exposing calendar to scope (or even just $scope.fullCalendar or $scope.calendar versus $scope.calendar.fullCalendar) is a very useful thing.

**Comment by joshkurz** [comment]
events is watched, but the length is watched instead of the actual
array itself. This is because it is good practice to watch tiny
incremental changes versus large obects inside of an array. What if the
calendar had 10000 events. First off I would not suggest having all of
these in the scope at once, but even still watching the length of the array
is much lighter on the ui then having to watch the entire array. Plus the
calendar would not even fire if we watched the array itself. Watch is a
tricky devil sometimes. I like to keep the watches as simple as possible.

That being said, the calendar is using the eventSources object
so theoretically we could watch a number of different arrays and update the
calendar accordingly. This could be very cumbersome if we used a loop to go
through all of the eventSources and placed a watch on each. I chose to just
watch one array of events that would be used to play with angular and then
any other eventSource object added would need to be added to the
eventSources array and the calendar would subsequently need to be updated
after the digest. I know this takes away some angular magic, but I believe
its better to have a fully functional calendar that works in all aspects
and environments then to try to make the directive update itself on every
change to any eventSource that could ever be.

I dont think its possible to expose the fullCalendar method to the scope
and have just scope.fullCalendar() the scope.calendar object is returned by
the initial fullCalendar call to set up the directive. This object exposes
the fullCalendar method.

Glad we are on the same page about exposing the calendar object. If you
know of a way to just expose the method call to the scope then please share.

I would like nothing more than for this calendar to be simple, effective,
and have the ability to be the base for any super advanced calendar that is
utilizing angular to help drive its success. If you have any more ideas,
then please share away.

On Thu, Jan 24, 2013 at 10:03 PM, oevna notifications@github.com wrote:

> Not having an $scope variable watched by Angular removes some of the magic
> of Angular, IMO. But I definitely think exposing calendar to scope (or even
> just $scope.fullCalendar or $scope.calendar versus
> $scope.calendar.fullCalendar) is a very useful thing.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/380#issuecomment-12685993.

## 

_Josh Kurz_
http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com

**Comment by joshkurz** [comment]
I have actually solved this issue all around with #372. The calendar watches every event source's length and the main event source array's length as well.
