### ISSUE TITLE
Initial ngModel value not selected in select2 with optgroup

### ISSUE THREAD

**Issue by akimball** [angular-ui/angular-ui-OLDREPO#402]
When using When using select2 with optgroup the initial ngModel value is not selected.

With the following an initial `selectedItem` is not selected

``` html
<select ui-select2 ng-model="selectedItem" style="width:300px;">
    <optgroup  ng-repeat="group in groupedData" label="{{group.text}}">
        <option ng-repeat="item in group" value="{{item.id}}" >{{item.text}}</option>
    </optgroup>
</select>
```

Setting `selectedItem` subsequently will update the select correctly (and this is what I'm doing as a workaround).

Without optgroup this all works as expected and the initial `selectedItem` is selected

``` html
<select ui-select2 ng-model="selectedItem" style="width:300px;">
    <option ng-repeat="item in data" value="{{item.id}}" >{{item.text}}</option>
</select>
```

The problem seems to be that a watch is set up on the option's ngRepeat expression, which doesn't work when there are optgroups.

**Comment by ProLoser** [comment]
Since a `<select>` will always have `<option>` tags inside, we can just change the selector.

**Comment by ProLoser** [comment]
Actually with this line: https://github.com/angular-ui/angular-ui/blob/master/modules/directives/select2/select2.js#L24 it should work fine. I'm not sure why it isn't working? Is it only the groupedData that is changing instead of the option data? Although that too shouldn't make sense.

Maybe it's a byVal vs byRef issue?

**Comment by akimball** [comment]
I realised I hadn't close my `<optgroup>` tag so I've updated the original issue. 

https://github.com/angular-ui/angular-ui/blob/master/modules/directives/select2/select2.js#L24 results in a watch on the options dataset which, when nested under an `optgroup`, is on the wrong scope (in my example `group` is not on the scope being watched).

Changing [line #24](https://github.com/angular-ui/angular-ui/blob/master/modules/directives/select2/select2.js#L24) to

``` javascript
repeatOption = tElm.find( 'optgroup[ng-repeat], optgroup[data-ng-repeat], option[ng-repeat], option[data-ng-repeat]' );
```

... gives me the result I want because it watches `groupedData` which is on the watched scope, but I'm not sure whether it will have other side-effects for that watch.

**Comment by ProLoser** [comment]
Hmmmm........

So I would have said do `$parent.options` but that doesn't fix it because inside the directive, I can't access the scope being watched.

For YOUR use-case, that change fixes it, but if someone changes the options array (and doesn't touch the opt-group level at all) the changes won't get updated. SO how do we follow changes on a deeper level?

**Comment by ProLoser** [comment]
After reviewing the code, no, it won't have any effects on the watch, but the selector should be made shallow as a security precaution.

Instead of `.find()` it should probably be `.children()` so that it doesn't go an extra level deeper and watch things that don't even exist on that scope.

I am thinking about adding support for a `ui-refresh` attribute as i've used elsewhere. You would be able to specify any arbitrary expression of your choice for watching and refreshing. It's still not a permanent solution however.

**Comment by Vilakshan** [comment]
Hello all,

I am using <select> with ng-options and facing same issue, Initial ngModel value is not selected in select2 when page gets loaded.

``` html
<select ui-select2  class="selet2styling"   ng-options="part.Id as part.Number for part in parts" ng-model="appSetting.PartId" data-placeholder="Select part" >
<option></option>
</select>
```

**Comment by ProLoser** [comment]
@Vilakshan there is a large disclaimer saying that `uiSelect2` is incompatible with `ngOptions`, you are supposed to use `<option ngRepeat>`

**Comment by Vilakshan** [comment]
@DeanSofer Yes you are right uiSelect2 is incompatible with ngOptions, I used option tag with ngRepeat. which solves the problem of Initial ngModel value selection in select2 dropdown.

But there is also an issue with using option tag with ngRepeat., In the code given below :- 

![Untitled](https://f.cloud.github.com/assets/2322486/151794/d19d2290-7598-11e2-8d38-99d81b7c1f14.png)

when page gets loaded i am bringing data from server and initial value in my ngModel "appSetting.PartId" is an Integer value, but after rendering of select2, the integer value automatically gets converted into a string value. which causes my form to become dirty. Is there any way to slove it..?

**Comment by ProLoser** [comment]
No. Not really.

## 

Dean Sofer
DeanSofer.com
714.900.2254

**Comment by jvoll** [comment]
I am having the same issue with string/int conversion. I can fix this down the line, but it would be nice if my integer values weren't automatically converted into strings.

**Comment by dnordberg** [comment]
Akimball's solution works for me. Would be nice to have this (Or an alternative fix) merged.

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-select2 (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-select2

Please reopen this issue there if it is still relevant.
