### ISSUE TITLE
ui-select2 ng-readonly integration

### ISSUE THREAD

**Issue by akoshelev** [angular-ui/angular-ui-OLDREPO#423]
Hi everyone,

Currently ui-select2 ignores ng-readonly directive. I realized that this is something that our team would like to have. What do you think - should it be placed as a part of angular-ui? If so, may I suggest to create a pull request for this?

**Comment by ProLoser** [comment]
Heh, "pool request".

I didn't know there **was** an ng-readonly directive. Learned something new...

Sure, go ahead and open a PR.

Look at the code that watches the 'disabled' attribute and model it in the same way.

You may even be able to supplement that code instead of creating completely new code.

Also, I would check if select2 natively supports readonly, and if not open a PR there. I'm getting the impression that readonly is almost the same as disabled?

**Comment by akoshelev** [comment]
Hi!
I have checked the implementation of select2. it supports both readonly and disabled attributes **but** applies 'disabled' in any case `if (opts.element.is(":disabled") || opts.element.is("[readonly='readonly']")) this.disable();`.  

As far as I know the main difference between readonly and disabled is that readonly elements support focusing and copying data from them. So I think it would be useful to have both readonly and disabled, but it may break backward compatibility for select2 functionality.

I will address this issue to the select2 team and will keep you in touch.

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-select2 (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-select2

Please reopen this issue there if it is still relevant.
