### ISSUE TITLE
Calendar is broken in angular-ui 0.4.0

### ISSUE THREAD

**Issue by yanl** [angular-ui/angular-ui-OLDREPO#427]
The calendar directive is not loading events. The demo page output multiples "equalsTracker is not defined" errors.

**Comment by joshkurz** [comment]
The controller needs to be updated to include event sources rather than an
event object. Ill get on this. There is an open issue to update the
calendar on the ghPages.

On Thu, Feb 14, 2013 at 12:17 AM, Yan Leroy notifications@github.comwrote:

> The calendar directive is not loading events. The demo page output
> multiples "equalsTracker is not defined" errors.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/427.

## 

_Josh Kurz_
http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com

**Comment by yanl** [comment]
Hi,
After passing an event sources array, the events do load, but there's still that "equalsTracker is not defined" error.

**Comment by joshkurz** [comment]
yes your right. There is a bug in the master branch. I am fixing it right
now. equalsTracker was not initialized. my mistake. thanks for reporting
this.

On Thu, Feb 14, 2013 at 1:30 AM, Yan Leroy notifications@github.com wrote:

> Hi,
> After passing an event sources array, the events do load, but there's
> still that "equalsTracker is not defined is not defined" error.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/427#issuecomment-13535058.

## 

_Josh Kurz_
http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com
