### ISSUE TITLE
select2 bug when programmatically clear value

### ISSUE THREAD

**Issue by bekos** [angular-ui/angular-ui-OLDREPO#447]
When we allowClear for a select2 and we press the little x icon, the model value is set to null.

When we programmatically set the value of the model to null, the select2 breaks with an error, and its value doesn't clear.

Plunker: http://plnkr.co/edit/KflJsN?p=preview

**Comment by ProLoser** [comment]
Nice catch. The recent updates broke this.

This section: https://github.com/angular-ui/angular-ui/blob/master/modules/directives/select2/select2.js#L46-L66

probably needs a few more if-checks for false or null and to use `select2('data')` instead of `select2('val')`.

@bekos do you think you'd be willing to help us out by taking a look at this and submitting a patch?

Also, @joseym i think this should be fairly straightforwards to address (in the way I described). We just need to thoroughly check that singles, multiples, `<select>` and `<input>` cases are all accounted for.

**Comment by ProLoser** [comment]
Can you test out this version with the latest version of select2? https://github.com/ProLoser/angular-ui/blob/select2/modules/directives/select2/select2.js

**Comment by ProLoser** [comment]
Opened #457 but needs unit tests

**Comment by rosslavery** [comment]
Just to add, I tested the version from #457 and it's still not working when resetting the value programmatically. The model value is updated correctly, but select2 does not revert to a null state.

I should add, my use-case is with a `<select>` using `<option ng-repeat>`, so the !isSelect check wouldn't work in my case.

**Comment by DiegoPires** [comment]
Hey guys, is this a problem specific for IE8? Because in IE8 when I set the model of a select2 to null it breaks it, and it don't return any more value from the model besides null...

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-select2 (after confirming it's still necessary with the latest code)?

**Comment by bekos** [comment]
OK. I will look into it.

**Comment by sivarajagopal** [comment]
how to clear the selected items from the select2 controls
