### ISSUE TITLE
how to set datepicker date format?

### ISSUE THREAD

**Issue by flyingnn** [angular-ui/angular-ui-OLDREPO#47]
how to set datepicker date format?

**Comment by ProLoser** [comment]
pass any options you would normally pass to $.fn.datepicker() as the expression.

So you can do something like `ui-date="{ dateFormat: 'yy-mm-dd' }"`

You may also want to instead simply declare these options as a default using `ui.config`

**Comment by ProLoser** [comment]
So I just realized this wasn't clarified on the docs. If you get it to work, it would be awesome if you helped us by adding your notes to the demo!

Everyone is running around so much every little bit helps

**Comment by flyingnn** [comment]
<code>
<input ui-date="{ dateFormat: 'yy-mm-dd' }" type="date" ng-model="item_in.date_in" name="date_in" id="date_in"  required/>
<tt>item_in = {{item_in}}</tt><br/>
</code>

when i select a date, textbox display formated date:2012-07-02
but {{item_in}} display other format date:{"date_in":"2012-07-01T16:00:00.000Z"} , i want it display 2012-07-02 too.

code: http://pastebin.com/gCq3QiwN

**Comment by flyingnn** [comment]
Results were affected by  line 98 at angular-ui.js :

<code>
return controller.$setViewValue(element.datepicker("getDate"));
</code>

**Comment by ProLoser** [comment]
pinging @dandoyon and @petebacondarwin again (sorry to keep bugging you guys).

Not sure who wanted to make the call, but it seems datepicker('getDate') returns the value in the same, standardized format. I understand jQueryUI's reasoning for this (since you would normally parse INTO this format for calculations elsewhere anyway) but perhaps it may be best to simply set the model value to be equivalent to the input value. In other words, simply use `element.val()` (or alternative solution for non-inputs)?

**Comment by flyingnn** [comment]
cool! work!

<code>
return controller.$setViewValue(element.val());
</code>

**Comment by petebacondarwin** [comment]
The date picker actually returns a real javascript date object, not a string.  This allows you to do stuff with the date such as 

```
<input ui-date ng-model="myDate"></input>
{{ myDate.toLocaleDateString() }}
```

I have updated the demo page, http://angular-ui.github.com/, to show this more clearly.

This is much more powerful than a string.  I would rather we kept it as it is than making it return a string.

What we could easily do is create a date format filter to give something like

```
{{ myDate | format : 'mm dd YYYY' }}
```

or we could create an additional directive (ui-formatdate?) or option on the ui-date directive to add a formatter to the ng-model formatting pipeline.

**Comment by dandoyon** [comment]
@petebacondarwin and @ProLoser, in my uiCurrency I wrapped the currencyFilter and passed in the symbol attribute using ui-config. I like the uniformity of ui-config. I do have an issue that I've meaning to bring up. I will create a separate issue for tracking. I agree with your assessment Pete on the value of having the object as opposed to a string. Allowing the user to decide on the global default format and then tweaking on a per element basis may work. We could add some convenience attributes for the overrides. my 2c

**Comment by ajoslin** [comment]
Angular has an internal date filter, so you can just do:

``` html
<input ui-date ng-model="myDate">
{{myDate | date:'shortTime'}}, {{myDate | 'mm dd YY'}}
```

http://docs.angularjs.org/api/ng.filter:date

**Comment by petebacondarwin** [comment]
Et voila!

On 12 July 2012 17:15, Andy Joslin <
reply@reply.github.com

**Comment by ProLoser** [comment]
Very cool. I still think however that you suggest a good idea in adding an option to have the model === the value. Isn't the inconsistency between the form value and the model value likely to cause unusual discrepencies (outside of just the developers knowledge)? For instance, lets say someone programmatically sets the datetime WITHOUT using a datepicker, what does the ng-model become now?

Perhaps a 'formatValue': true option would be enough since I know I personally don't need this date object and was expecting the format to be sent to the backend.

**Comment by petebacondarwin** [comment]
Hi Dean
I am not quite sure what you mean by mode === value.  Do you mean that the
value of ng-model is to be the same as the value of element.val()?  This
doesn't make sense to me as the whole point is that the view can be
different from the model - hence the formatters and parsers.  The date
directive is clever enough to update if you change the ng-model value -
this is what the $render method does.
Pete

On 12 July 2012 21:37, Dean Sofer <
reply@reply.github.com

**Comment by ProLoser** [comment]
Fair enough, it was something I was thinking about and didn't know what other people felt. At the very least then I believe we should clearly clarify on the docs and demo that your ng-model will be a Date object and not the string that you are formatting for. We should also provide an example of working with the ng-model value in the formatted state you were hoping for (so that other people don't raise this very same issue again in the future).

My concern was what if someone does something like `$scope.dateModel = '05/02/1987';`? Will this break, will the view value reflect the date accurately? Should people be aware that the value will be (immediately) converted to a Date object? Is the value changed to a date object? If all of these answers are 'no' then should we be expecting people to set $scope.dateModel to a date object or is that an unreasonable expectation?

These were the sort of questions that occur to me.

**Comment by ProLoser** [comment]
@flyingnn I'm going to go ahead and close this issue as I think Pete makes a good point that you have more control using the date object than you otherwise would. He updated the demo page to provide examples of how you may go about formatting your model data to reflect your formatted date.

I think we are probably going to shift into this direction of having the model contain a richer form of information than the view with more and more directives (such as Select2 having an object rather than just a string)

**Comment by whitneyland** [comment]
I would request this issue be reopened for discussion, as ProLoser is on the right track here.

While it's true that a real object is _usually_ better than a string representation, Date is a special problem case because JSON has no concept of it.

In practice, data designs are moving towards representing Dates in JSON using a UTC/ISO string, so two-way binding can't work well most modern services if you bind the model to a Date object.

Maybe the best of both worlds is to allow binding to a UTC string, and rely on a convenience method to create a Date instance as needed.

Without 2-way binding to UTC, extra cruft code is required that is not as intuitive as using a getDateObject as needed.

**Comment by petebacondarwin** [comment]
```
<input ng-model="myISODateString" ui-date ui-date-format>
```

should give you what you want - note the empty `ui-date-format` directive that indicates that the model is a string with ISO date format.
Then in you own code you can convert this back to a `Date` object if you need it:

```
scope.myActualDateObj = new Date(scope.myISODateString);
```

**Comment by whitneyland** [comment]
Thanks, seems to work for default formatting.
However, does it mean you lose control over formatting?
This way seems to bind to ISO and allows formatting, but doesn't work on first display (once you pick a date it displays correctly):http://plnkr.co/edit/Q2uMgE?p=preview

Date: Fri, 8 Mar 2013 14:50:05 -0800

**Comment by alendsnap** [comment]
This is the easiest workaround I've found to set a **formatted date string** on a model with `ui-date`:
```
    <input
      type="text"
      class="form-control"
      placeholder="Date (mm/dd/yyyy)"
      ng-model="dateObj"
      ng-change="vm.dateString = (dateObj | date: 'MM/dd/yyyy')"
      ui-date
      required
    >
```

The input uses its own date object, and when its value changes I format and set the date string on my model.
Hope it helps someone else.

**Comment by codealchemist** [comment]
This is the easiest workaround I've found to set a **formatted date string** on a model with `ui-date`:

```
    <input
      type="text"
      class="form-control"
      placeholder="Date (mm/dd/yyyy)"
      ng-model="dateObj"
      ng-change="vm.dateString = (dateObj | date: 'MM/dd/yyyy')"
      ui-date
      required
    >
```

The input uses its own date object, and when its value changes I format and set the date string on my model.
Hope it helps someone else.
