### ISSUE TITLE
angular-ui.github.com

### ISSUE THREAD

**Issue by dandoyon** [angular-ui/angular-ui-OLDREPO#49]
Pretty slow, blocking on jsfiddle, I think we should consider making it more of an informational page without the running app for now.

**Comment by petebacondarwin** [comment]
Can you clarify what is slow.  The index.html is running up fine for me.  What do you mean by "blocking on jsfiddle"?

**Comment by dandoyon** [comment]
I think my coffee hadn't kicked in yet, I misspoke, it was library coming from raw.github.com.  In some respect, I kinda feel like we  should be pulling from a CDN instead of github (IMHO).

**Comment by ProLoser** [comment]
I'm confused too, are you referring to the demo page? The page itself is hosted on github, so it would only make sense to have the assets hosted there too. If you're referring to using jsFiddle with assets hosted on github, well I didn't know we have a special jsFiddle.

**Comment by dandoyon** [comment]
sorry for confusion the demo page, when I look at index.html I see lots of references to 3rd party apps strewn amongst the internet. And I take back, what I took back before (jsfiddle) I now recall "fiddle" -- which seems to be for the tinymce app.

make sense?

--dan

**Comment by ProLoser** [comment]
Ah you're saying we should standardize the references to third party libs. I actually figured this might come up sooner or later. Honestly I didn't figure there was a good approach for this (and those plugins may not even have CDN locations). Perhaps the best solution would be to do lazy-loading so that directives who rely on plugins that failed to load will not be instantiated (and therefore will not cause errors for the rest of the page). Alternatively we could just break the demo page into separate pages.

If you have better URLs to use for third-party libs feel free to update them. In fact, we could even consider adding these third party plugins as submodules, but I do not think it's a good idea to explicitly add their code to our repo. Maybe putting submodules into a lib/ folder is enough, as it works excellently for the angular-ui repo.

**Comment by ProLoser** [comment]
This issue is on the wrong repo (just realized). I added angular-ui.github.com to our team so you will now be notified about bug tickets on there too.

**Comment by dandoyon** [comment]
sorry, should've posted there..
