### ISSUE TITLE
prevent default and stop propagation

### ISSUE THREAD

**Issue by clkao** [angular-ui/angular-ui-OLDREPO#513]
Hi,

these seem rather commonly used for fixing ng-click/ng-href issues.  should i package them up as a module?  any suggested namespace?

angular.module('app.directives', [])
.directive('ngxNoclick', function(){
  return function($scope, element, attrs){
    return $(element).click(function(it){
      it.preventDefault();
      return false;
    });
  };
})
.directive('ngxFinal', function(){
  return function($scope, element, attrs){
    return $(element).click(function(it){
      return it.stopPropagation();
    });
  };
});

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-utils (after confirming it's still necessary with the latest code)?

Feel free to open a pull request on a  new branch so that we can provide feedback :smile:

**Comment by wesleycho** [comment]
If you feel this is still an issue, I recommend filing a new issue with the `ui-utils` repository - note that ng-click gives you access to event through the `$event` parameter in the callback though.
