### ISSUE TITLE
CodeMirror exception on ui-refresh

### ISSUE THREAD

**Issue by damiengenet** [angular-ui/angular-ui-OLDREPO#544]
With AngularUI 0.4.0 and CodeMirror 3.0.4, when the ui-refresh is fired the following exception is thrown:

"""
Error: cm is undefined
clearCaches@http://localhost:8080/[..]/lib/codemirror-3.02/lib/codemirror.js:982
CodeMirror.prototype.refresh@http://localhost:8080/[..]/lib/codemirror-3.02/lib/codemirror.js:2854
e/f<@http://localhost:8080/[..]/lib/angular/angular.min.js:101
e@http://localhost:8080/[..]/lib/angular/angular.min.js:30
vc/f.defer/c<@http://localhost:8080/[..]/lib/angular/angular.min.js:33

http://localhost:8080/[..]/lib/angular/angular.min.js
Line 62
"""

It seems like this comes from the fact that the refresh is called with "$timeout(codeMirror.refresh);" without binding the code mirror object. CodeMirror refresh function uses a reference to "this":
"""
    refresh: function() {
      clearCaches(this);
      [..]
    }
"""

**Comment by douglasduteil** [comment]
Yep. Strange... Here is [a buggy demo](http://jsbin.com/ohibuw/1/edit) that throws a TypeError but still works...

It's already fixed in the [angular-ui/ui-codemirror](https://github.com/angular-ui/ui-codemirror) repo ([demo](http://jsbin.com/itasam/1/edit))

_PS : I didn't find [CodeMirror version 3.0.4](https://github.com/marijnh/CodeMirror/tags) so I'm just using the version 3.12 here_

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate to https://github.com/angular-ui/ui-codemirror (after confirming it's still necessary with the latest code)?
