### ISSUE TITLE
ui-utils vs angular-ui

### ISSUE THREAD

**Issue by CMCDragonkai** [angular-ui/angular-ui-OLDREPO#564]
On the main angular-ui site, the downloads to "angular-ui" in general seems to have disappeared, instead it has been replaced with links going to separate modules such ui-utils.. etc.

Is it telling us to download utils and the modules separately rather than this repo.

If so, what is the use of this angular-ui repo? Is it just staging ground for all the other modularised angular ui packages?

Furthermore is the angular-ui css required anymore? Also what are the differences? Why is currency left out? Why is there no build directory for the ui-utils package, since some like the "reset" module has a custom css that needs to be included. Now I have to rummage through the folders to find any possible css that I need to include.

**Comment by ProLoser** [comment]
@CMCDragonkai this repo is vestigial and in the future may eventually be removed. This project has been broken apart into more manageable sub-projects, and their requirements are handled individually.

ui-utils is collection of 0-external-dependency utilities which I **HIGHLY** recommend using on any/every project, even if you're using ui-bootstrap. The rest of the modules are for you to pick and choose on a need-by-need basis, but they will have their own dependencies.

Currency is discontinued because it was developed before the `ng-class="{className:value}"` was available, which renders it mostly useless.

`ui-if` has been discontinued because it's been merged into the core as `ng-if` in the v1.1.x branch.

Again, ui-utils has 0 css dependency, although you will probably want to write your own for `ui-show` and `ui-hide` (which is probably going to be dropped in the near future too).

Yes, `ui-utils` does not have a build / dist folder. That's our fault, we just haven't had the time and are really reaching out for community champions to take over.

The `ui-reset` is a semi-crappy module and it came with 'suggested' css but again I might recommend rolling your own instead.

Sorry about all the confusion.

**Comment by CMCDragonkai** [comment]
I would prefer for this module not to be removed, because there may be production sites that rely on angular-ui. Better a soft transition.

**Comment by ProLoser** [comment]
This repo is not going anywhere for the time being. But I **do** recommend switching to more up-to-date solutions.
